# Reportagem: O impacto do reajuste das bolsas do CNPq e da CAPES para bolsistas do Ceará

Neste relatório, reunimos o código desenvolvido para a análise dos dados referentes ao valor pago para bolsistas do Conselho Nacional de Desenvolvimento Científico e Tecnológico (CNPQ) e da Coordenação de Aperfeiçoamento de Pessoal de Nível Superior (Capes) no Ceará e o impacto, para eles, do reajuste anunciado pelo Governo Federal em fevereiro de 2023.

Parte das informações coletadas neste notebook deram subsídio para a reportagem ["'A pesquisa, sem um pesquisador, não existe': o impacto do reajuste para bolsistas do Ceará"](https://mais.opovo.com.br/reportagens-especiais/2023/04/06/a-pesquisa-sem-um-pesquisador-nao-existe-o-impacto-do-reajuste-para-bolsistas-do-ceara.html), publicada no dia 6 de abril de 2023 no [O POVO+](https://mais.opovo.com.br/), plataforma exclusiva para assinantes do Jornal O POVO, de Fortaleza (CE).

**ÍNDICE**

1. [Leitura dos dados](#leitura)


2. [Cálculos e análises](#calculos)

    2.1 [Valor pago](#valor-pago)


3. [Dados do Ceará](#dados-ce)

    3.1 [CAPES + CNPQ](#capes-cnpq)


4. [Cruzamento com tabela de reajuste](#cruzamento-tabela)


5. [Distribuição das bolsas no Ceará](#distribuicao-bolsas-ce)

In [1]:
import pandas as pd

In [2]:
pd.options.display.float_format = '{:.2f}'.format

## 1. Leitura dos dados <a name="leitura"></a>

In [3]:
path = 'bases/'
arquivos = 'arquivos/'

In [4]:
df_2022 = pd.read_excel(path+'Relatorio_de_dados_abertos_CNPq_Jan-Dez2022.xlsx')
df_2022.columns = df_2022.iloc[3]
df_2022 = df_2022[4:]

In [5]:
df_2022.head(2)

3,Ano Referência,Processo,Data Início Processo,Data Término Processo,Beneficiário,Linha de Fomento,Modalidade,Categoria/Nível,Nome Chamada,Programa CNPq,...,Sigla UF Destino,Região,País Destino,Título do Projeto,Palavra Chave,Plano Interno,UO,Fonte Recurso,Natureza de Despesa,Valor Pago
4,2022,372325/2022-0,2021-09-01 00:00:00,2022-08-31 00:00:00,Josemar Hipólito da Silva,Bolsas de Apoio Técnico,ATP - Apoio Técnico em Extensão no País,A,JOSE.ELOIZIO - PRORROGAÇÃO PROJETO CHAMADA 21/...,Programa de Tecnologia e Inovação para Agropec...,...,SE,NE,BRA - Brasil,Projeto de Criação do Núcleo de Estudo em Agro...,NaN,0000,"MINIST.DA CIENCIA,TECNOL.,INOV.E COMUNICACOES",0190000000,339018,1100
5,2022,372329/2022-5,2022-09-01 00:00:00,2023-08-31 00:00:00,Mislene Pereira da Silva,Bolsas de Extensão em Pesquisa,EXP - Extensão no País,C,JOSE.ELOIZIO - PRORROGAÇÃO PROJETO CHAMADA 21/...,Programa de Tecnologia e Inovação para Agropec...,...,SE,NE,BRA - Brasil,Projeto de Criação do Núcleo de Estudo em Agro...,NaN,0000,"MINIST.DA CIENCIA,TECNOL.,INOV.E COMUNICACOES",0190000000,339018,1100

In [6]:
df_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167249 entries, 4 to 167252
Data columns (total 30 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Ano Referência             167249 non-null  object
 1   Processo                   167249 non-null  object
 2   Data Início Processo       167249 non-null  object
 3   Data Término Processo      167249 non-null  object
 4   Beneficiário               167249 non-null  object
 5   Linha de Fomento           167249 non-null  object
 6   Modalidade                 167249 non-null  object
 7   Categoria/Nível            40311 non-null   object
 8   Nome Chamada               167249 non-null  object
 9   Programa CNPq              167249 non-null  object
 10  Grande Área                167249 non-null  object
 11  Área                       167188 non-null  object
 12  Subárea                    167249 non-null  object
 13  Instituição Origem         166232 non-null  object
 14  Sigla UF Origem            165751 non-null  object
 15  País Origem                167249 non-null  object
 16  Instituição Destino        167249 non-null  object
 17  Sigla Instituição Destino  167245 non-null  object
 18  Sigla Instituição Macro    167248 non-null  object
 19  Cidade Destino             167226 non-null  object
 20  Sigla UF Destino           167249 non-null  object
 21  Região                     167249 non-null  object
 22  País Destino               167249 non-null  object
 23  Título do Projeto          149741 non-null  object
 24  Palavra Chave              31711 non-null   object
 25  Plano Interno              167240 non-null  object
 26  UO                         167249 non-null  object
 27  Fonte Recurso              167249 non-null  object
 28  Natureza de Despesa        167240 non-null  object
 29  Valor Pago                 167249 non-null  object
dtypes: object(30)
memory usage: 38.3+ MB

In [7]:
df_2022['Área'].unique()

array(['Engenharia Elétrica', 'Multidisciplinar', 'Geociências',
       'Química', 'Ciências Ambientais', 'Zoologia', 'Ecologia',
       'Comunicação', 'Engenharia Aeroespacial', 'Engenharia Química',
       'Engenharia de Minas', 'História', 'Ciência da Informação',
       'Administração', 'Ciência da Computação', 'Física',
       'Engenharia Nuclear', 'Astronomia', 'Biologia Geral', 'Matemática',
       'Agronomia', 'Bioquímica', 'Engenharia Agrícola',
       'Engenharia de Produção', 'Engenharia Mecânica',
       'Engenharia de Materiais e Metalúrgica', 'Medicina',
       'Medicina Veterinária', 'Biotecnologia', 'Engenharia Sanitária',
       'Microbiologia', 'Saúde Coletiva', 'Farmácia',
       'Engenharia de Energia', 'Divulgação Científica',
       'Planejamento Urbano e Regional', 'Odontologia', 'Filosofia',
       'Ciência Política', 'Sociologia', 'Psicologia', 'Geografia',
       'Educação', 'Fonoaudiologia', 'Fisioterapia e Terapia Ocupacional',
       'Antropologia', 'Lingüística', 'Genética', 'Economia', 'Direito',
       'Letras', 'Recursos Pesqueiros e Engenharia de Pesca', 'Artes',
       'Turismo', 'Enfermagem', 'Ciência e Tecnologia de Alimentos',
       'Recursos Florestais e Engenharia Florestal', 'Museologia',
       'Botânica', 'Serviço Social', 'Demografia', 'Farmacologia',
       'Meio Ambiente e Sustentabilidade', 'Engenharia Civil',
       'Fisiologia', 'Tecnologias Médicas e da Saúde', 'Biofísica',
       'Zootecnia', 'Probabilidade e Estatística', 'Educação Física',
       'Engenharia Biomédica', 'Robótica, Mecatrônica e Automação',
       'Oceanografia', 'Arquitetura e Urbanismo', 'Nutrição',
       'Microeletrônica', 'Desenho Industrial', 'Imunologia',
       'Parasitologia', 'Arqueologia', 'Engenharia de Transportes',
       'Morfologia', 'Biomedicina', 'Engenharia Mecatrônica', 'Teologia',
       'Defesa', 'Energia', 'Tecnologias Digitais',
       'Tecnologias de Produção Industrial e de Serviços',
       'Tecnologias Médicas e da Saúde ', 'Engenharia Naval e Oceânica',
       nan, 'Nanotecnologia e Novos Materiais',
       'Tecnologias de Materiais', 'Economia Doméstica',
       'Biodiversidade e Recursos Naturais',
       'Tecnologias Sociais e Educacionais',
       'Tecnologias Educacionais e Sociais',
       'Tecnologia e Inovação para Agropecuária',
       'Biotecnologia (Tecnologias)', 'Tecnologias Agrárias',
       'Tecnologias para o Desenvolvimento Sustentável',
       'Áreas Tecnológicas de Física e Matemática',
       'Tecnologia da Informação e Comunicação', 'Tecnologias Ambientais',
       'Áreas Tecnológicas de Química e Geociências',
       'Tecnologias nas áreas Aeronáutica e Aeroespacial', 'Bioética',
       'Desenvolvimento Tecnológico e Industrial', 'Mudanças Climáticas',
       'Tecnologias Naval e Marítima', 'Complexo da Defesa',
       'Ciências Sociais'], dtype=object)

In [8]:
df_2022['Subárea'].unique()

array(['Materiais Condutores', 'Ensino', 'Geologia Ambiental', ...,
       'Oceanografia', 'Artes', 'Geodésia Geométrica'], dtype=object)

In [9]:
df_2022['Instituição Destino'].unique()

array(['Universidade Federal de Sergipe',
       'Ministério da Ciência, Tecnologia e Inovações',
       'Universidade Federal do Ceará', ...,
       'Instituto de Catálisis y Petroleoquímica',
       'Ministério da Agricultura, Pecuária e Abastecimento',
       'CONSULADO GERAL DA SUICA NO RIO DE JANEIRO '], dtype=object)

In [10]:
df_2022['Instituição Origem'].unique()

array(['Universidade Federal de Sergipe',
       'Ministério da Ciência, Tecnologia e Inovações',
       'Universidade Federal do Ceará', ...,
       'Instituto de Catálisis y Petroleoquímica',
       'Ministério da Agricultura, Pecuária e Abastecimento',
       'CONSULADO GERAL DA SUICA NO RIO DE JANEIRO '], dtype=object)

## 2. Cálculos e análises <a name="calculos"></a>

In [11]:
(df_2022['Instituição Destino'] == df_2022['Instituição Origem']).value_counts()

True     164698
False      2551
dtype: int64

In [12]:
df_2022['Valor Pago'] = df_2022['Valor Pago'].astype(float)

In [13]:
df_2022['dtg_inicio'] = pd.to_datetime(df_2022['Data Início Processo'])

In [14]:
df_2022['dtg_fim'] = pd.to_datetime(df_2022['Data Término Processo'])

In [15]:
resumo_uf = df_2022.groupby('Sigla UF Destino').size().reset_index()

resumo_uf.columns = ['uf','qtd']

resumo_uf.sort_values(by='qtd')

          uf    qtd
3         AP    274
0         AC    300
22        RR    315
21        RO    509
8   Exterior    752
27        TO    755
17        PI   1213
1         AL   1360
10        MA   1375
25        SE   1650
7         ES   1835
13        MT   1836
2         AM   1872
12        MS   2075
20        RN   3106
9         GO   3122
14        PA   3836
15        PB   4294
5         CE   4500
4         BA   5397
24        SC   5890
16        PE   6119
6         DF   8777
18        PR   8934
23        RS  13997
11        MG  14946
19        RJ  33809
26        SP  34401

In [16]:
resumo_uf_modalidade = df_2022.groupby(['Sigla UF Destino','Modalidade']).size().reset_index()

resumo_uf_modalidade.columns = ['uf','modalidade','qtd']

resumo_uf_modalidade

     uf                                 modalidade  qtd
0    AC                   APQ - Auxílio a Pesquisa   11
1    AC      ARC - Promoção de Eventos Científicos    1
2    AC  DCR - Desenvolvimento Cientifico Regional    5
3    AC                     EXP - Extensão no País    3
4    AC                              GM - Mestrado    3
..   ..                                        ...  ...
570  TO   ITI - Iniciação Tecnológica e Industrial   38
571  TO                 PDJ - Pós-doutorado Júnior    2
572  TO             PQ - Produtividade em Pesquisa   24
573  TO                 PV - Pesquisador Visitante    1
574  TO          SET - Fixação de Recursos Humanos    2

[575 rows x 3 columns]

In [17]:
total_uf_modalidade = resumo_uf.copy()

total_uf_modalidade['modalidade'] = 'Todas'

total_uf_modalidade = pd.concat([total_uf_modalidade,resumo_uf_modalidade])

total_uf_modalidade

     uf   qtd                                modalidade
0    AC   300                                     Todas
1    AL  1360                                     Todas
2    AM  1872                                     Todas
3    AP   274                                     Todas
4    BA  5397                                     Todas
..   ..   ...                                       ...
570  TO    38  ITI - Iniciação Tecnológica e Industrial
571  TO     2                PDJ - Pós-doutorado Júnior
572  TO    24            PQ - Produtividade em Pesquisa
573  TO     1                PV - Pesquisador Visitante
574  TO     2         SET - Fixação de Recursos Humanos

[603 rows x 3 columns]

In [18]:
resumo_uf_gArea = df_2022.groupby(['Sigla UF Destino','Grande Área']).size().reset_index()

resumo_uf_gArea.columns = ['uf','grande_area','qtd']

resumo_uf_gArea

     uf                  grande_area  qtd
0    AC            Ciências Agrárias   86
1    AC          Ciências Biológicas   39
2    AC   Ciências Exatas e da Terra   25
3    AC             Ciências Humanas   41
4    AC   Ciências Sociais Aplicadas    5
..   ..                          ...  ...
277  TO            Ciências da Saúde   60
278  TO                  Engenharias  176
279  TO  Lingüística, Letras e Artes   26
280  TO                        Outra    3
281  TO                  Tecnologias   34

[282 rows x 3 columns]

In [19]:
total_uf_gArea = resumo_uf.copy()

total_uf_gArea['grande_area'] = 'Todas'

total_uf_gArea = pd.concat([total_uf_gArea,resumo_uf_gArea])

total_uf_gArea

     uf   qtd                  grande_area
0    AC   300                        Todas
1    AL  1360                        Todas
2    AM  1872                        Todas
3    AP   274                        Todas
4    BA  5397                        Todas
..   ..   ...                          ...
277  TO    60            Ciências da Saúde
278  TO   176                  Engenharias
279  TO    26  Lingüística, Letras e Artes
280  TO     3                        Outra
281  TO    34                  Tecnologias

[310 rows x 3 columns]

### 2.1 Valor pago <a name="valor-pago"></a>

In [20]:
resumo_uf_pago = df_2022.groupby('Sigla UF Destino')['Valor Pago'].sum().reset_index()

resumo_uf_pago.columns = ['uf','R$']
total = resumo_uf_pago['R$'].sum()
resumo_uf_pago['pct'] = round(resumo_uf_pago['R$']/total * 100,2)

resumo_uf_pago.sort_values(by='R$', ascending=False).to_csv(arquivos+'valor_pct_por_uf.csv')
resumo_uf_pago.sort_values(by='R$', ascending=False)

          uf           R$   pct
26        SP 415665842.16 27.68
19        RJ 206128397.80 13.73
11        MG 159343106.43 10.61
23        RS 136088406.10  9.06
18        PR  79478384.77  5.29
6         DF  65749320.49  4.38
24        SC  60334558.27  4.02
4         BA  59219444.68  3.94
16        PE  51361551.90  3.42
8   Exterior  40015041.03  2.66
5         CE  30229987.97  2.01
15        PB  28628723.02  1.91
9         GO  27660680.21  1.84
14        PA  26355291.80  1.75
20        RN  19691894.09  1.31
2         AM  17964666.01  1.20
7         ES  13455119.13  0.90
12        MS  13050276.21  0.87
25        SE  10799925.62  0.72
13        MT   9737814.91  0.65
1         AL   7090757.80  0.47
10        MA   7089276.21  0.47
17        PI   5781315.05  0.38
27        TO   3688291.75  0.25
21        RO   3421147.99  0.23
3         AP   1385442.24  0.09
22        RR   1258873.22  0.08
0         AC   1160165.00  0.08

In [21]:
valor_br = resumo_uf_pago['R$'].sum()
valor_br

1501833701.8600001

In [22]:
valor_ce = resumo_uf_pago.loc[resumo_uf_pago.uf=='CE']['R$'].sum()
valor_ce

30229987.97

In [23]:
f'{round((valor_ce/valor_br)*100,2)}% do BR p/ o CE'

'2.01% do BR p/ o CE'

In [24]:
valor_sp = resumo_uf_pago.loc[resumo_uf_pago.uf=='SP']['R$'].sum()
valor_sp

415665842.16

In [25]:
f'{round((valor_sp/valor_br)*100,2)}% do BR p/ o SP'

'27.68% do BR p/ o SP'

In [26]:
resumo_uf_gArea = df_2022.groupby(['Sigla UF Destino','Grande Área'])['Valor Pago'].sum().reset_index()

resumo_uf_gArea.columns = ['uf','grande_area','R$']

resumo_uf_gArea

     uf                  grande_area        R$
0    AC            Ciências Agrárias 269400.00
1    AC          Ciências Biológicas  64800.00
2    AC   Ciências Exatas e da Terra  75000.00
3    AC             Ciências Humanas 112100.00
4    AC   Ciências Sociais Aplicadas  12400.00
..   ..                          ...       ...
277  TO            Ciências da Saúde 205150.00
278  TO                  Engenharias 999100.00
279  TO  Lingüística, Letras e Artes  89760.00
280  TO                        Outra  55517.15
281  TO                  Tecnologias 108300.00

[282 rows x 3 columns]

In [27]:
uf_modalidade = df_2022.groupby(['Sigla UF Destino','Modalidade'])['Valor Pago'].sum().reset_index()

uf_modalidade.columns = ['uf','modalidade','R$']

uf_modalidade

     uf                                 modalidade        R$
0    AC                   APQ - Auxílio a Pesquisa 442265.00
1    AC      ARC - Promoção de Eventos Científicos  50000.00
2    AC  DCR - Desenvolvimento Cientifico Regional 102800.00
3    AC                     EXP - Extensão no País   6600.00
4    AC                              GM - Mestrado  13500.00
..   ..                                        ...       ...
570  TO   ITI - Iniciação Tecnológica e Industrial  47200.00
571  TO                 PDJ - Pós-doutorado Júnior  49500.00
572  TO             PQ - Produtividade em Pesquisa 224740.00
573  TO                 PV - Pesquisador Visitante  40322.15
574  TO          SET - Fixação de Recursos Humanos  35000.00

[575 rows x 3 columns]

In [28]:
total_uf_modalidade = resumo_uf_pago.copy()

total_uf_modalidade['modalidade'] = 'Todas'

total_uf_modalidade = pd.concat([total_uf_modalidade,uf_modalidade])

total_uf_modalidade = total_uf_modalidade.fillna(0)

total_uf_modalidade[['uf','modalidade','R$']].to_csv(arquivos+'total_uf_modalidade.csv')
total_uf_modalidade[['uf','modalidade','R$']]

     uf                                modalidade          R$
0    AC                                     Todas  1160165.00
1    AL                                     Todas  7090757.80
2    AM                                     Todas 17964666.01
3    AP                                     Todas  1385442.24
4    BA                                     Todas 59219444.68
..   ..                                       ...         ...
570  TO  ITI - Iniciação Tecnológica e Industrial    47200.00
571  TO                PDJ - Pós-doutorado Júnior    49500.00
572  TO            PQ - Produtividade em Pesquisa   224740.00
573  TO                PV - Pesquisador Visitante    40322.15
574  TO         SET - Fixação de Recursos Humanos    35000.00

[603 rows x 3 columns]

In [29]:
# Beneficiários por UF:
beneficiarios_uf = df_2022.groupby('Sigla UF Destino')['Beneficiário'].nunique().reset_index().sort_values(by='Beneficiário', ascending = False)
beneficiarios_uf.columns = ['uf','qtd_beneficiarios']
total = beneficiarios_uf['qtd_beneficiarios'].sum()
# beneficiarios_uf['pct'] = (beneficiarios_uf['qtd_beneficiarios']/total)*100
beneficiarios_uf

          uf  qtd_beneficiarios
26        SP              26894
19        RJ              25970
11        MG              11919
23        RS              10873
18        PR               7479
6         DF               7410
16        PE               4879
24        SC               4751
4         BA               4436
5         CE               3544
15        PB               3488
14        PA               2970
9         GO               2653
20        RN               2537
12        MS               1761
13        MT               1640
7         ES               1513
2         AM               1491
25        SE               1404
10        MA               1233
1         AL               1087
17        PI               1045
27        TO                615
8   Exterior                608
21        RO                468
22        RR                282
0         AC                270
3         AP                242

In [30]:
beneficiarios_uf.to_csv(arquivos+'beneficiarios_uf.csv')

In [31]:
# Bolsas por UF:
bolsas_uf = df_2022.groupby('Sigla UF Destino').size().reset_index().sort_values(by=0, ascending = False)
bolsas_uf.columns = ['uf','qtd_bolsas']
bolsas_uf

          uf  qtd_bolsas
26        SP       34401
19        RJ       33809
11        MG       14946
23        RS       13997
18        PR        8934
6         DF        8777
16        PE        6119
24        SC        5890
4         BA        5397
5         CE        4500
15        PB        4294
14        PA        3836
9         GO        3122
20        RN        3106
12        MS        2075
2         AM        1872
13        MT        1836
7         ES        1835
25        SE        1650
10        MA        1375
1         AL        1360
17        PI        1213
27        TO         755
8   Exterior         752
21        RO         509
22        RR         315
0         AC         300
3         AP         274

In [32]:
resumo_uf_final = pd.merge(pd.merge(bolsas_uf,beneficiarios_uf),resumo_uf_pago[['uf','R$']])

In [33]:
resumo_uf_final.to_csv(arquivos+'resumo_uf_final.csv')

## 3. Dados do Ceará <a name="dados-ce"></a>

In [34]:
df_2022_ce = df_2022.loc[df_2022['Sigla UF Destino']== 'CE']

In [35]:
df_2022_ce.head(2)

3,Ano Referência,Processo,Data Início Processo,Data Término Processo,Beneficiário,Linha de Fomento,Modalidade,Categoria/Nível,Nome Chamada,Programa CNPq,...,País Destino,Título do Projeto,Palavra Chave,Plano Interno,UO,Fonte Recurso,Natureza de Despesa,Valor Pago,dtg_inicio,dtg_fim
2396,2022,180365/2022-3,2022-08-01 00:00:00,2026-07-31 00:00:00,Chrissandro Marques de Almeida,Bolsas de Iniciação Tecnológica e Industrial,ITI - Iniciação Tecnológica e Industrial,A,ICMBio 2017 - CHAMADA CNPQ/ICMBIO/FAPs nº 18/2...,PROGRAMA DE BIODIVERSIDADE,...,BRA - Brasil,"Cavernas, abrigos e seu ecossistema - Pesquisa...",NaN,04181502RCA,INST.CHICO MENDES DE CONSER.DA BIODIVERSIDADE,0307442070,339018,400.00,2022-08-01,2026-07-31
2397,2022,380673/2022-3,2022-09-01 00:00:00,2023-08-31 00:00:00,Jefferson Lima dos Santos,Bolsas de Desenvolvimento Tecnológico e Indust...,DTI - Desenvolvimento Tecnológico Industrial,C,ICMBio 2017 - CHAMADA CNPQ/ICMBIO/FAPs nº 18/2...,PROGRAMA DE BIODIVERSIDADE,...,BRA - Brasil,"Cavernas, abrigos e seu ecossistema - Pesquisa...",NaN,04181502RCA,INST.CHICO MENDES DE CONSER.DA BIODIVERSIDADE,0307442070,339018,1100.00,2022-09-01,2023-08-31

In [36]:
df_2022_ce['Modalidade'].nunique()

25

In [37]:
df_2022_ce['Modalidade'].value_counts().head(6)

IC - Iniciação Científica            2155
PQ - Produtividade em Pesquisa        567
ICJ - Iniciação Científica Júnior     558
IT - Iniciação Tecnológica            222
GM - Mestrado                         210
GD - Doutorado                        209
Name: Modalidade, dtype: int64

In [38]:
df_2022_ce['Modalidade'].value_counts().tail(19).sum()

579

In [39]:
df_2022_ce['Modalidade'].count()

4500

In [40]:
df_2022_ce['Modalidade'].value_counts().head(6).sum()

3921

In [41]:
df_2022_ce.loc[df_2022_ce['dtg_fim'].dt.year != 2022]['Modalidade'].value_counts()

IC - Iniciação Científica                       1182
PQ - Produtividade em Pesquisa                   311
ICJ - Iniciação Científica Júnior                290
IT - Iniciação Tecnológica                       122
GD - Doutorado                                   119
GM - Mestrado                                    109
APQ - Auxílio a Pesquisa                          99
SET - Fixação de Recursos Humanos                 55
DTI - Desenvolvimento Tecnológico Industrial      43
ITI - Iniciação Tecnológica e Industrial          25
ATP - Apoio Técnico em Extensão no País           24
AT - Apoio Técnico a Pesquisa                     17
DT - Produtividade Desen. Tec. e Extensão         17
EXP - Extensão no País                            14
PDJ - Pós-doutorado Júnior                        14
DCR - Desenvolvimento Cientifico Regional         12
ITC - Iniciação Tecnológica em TICs                5
ARC - Promoção de Eventos Científicos              4
AED - Auxílio a Editoração e Publicação            3
PV - Pesquisador Visitante                         2
EV - Especialista Visitante                        1
PDI - Pos-doutorado Empresarial                    1
PDS - Pós-doutorado Sênior                         1
Name: Modalidade, dtype: int64

In [42]:
df_2022_ce.loc[df_2022_ce['dtg_fim'].dt.year != 2022].shape[0]

2470

In [43]:
2470 - (1182+109+119)

1060

In [44]:
# Valor anterior (ICV / Me / Doc)
(1182*400)+(109*1500)+(119*2200)

898100

In [45]:
# Valor reajustado (ICV / Me / Doc)v
(1182*700)+(109*2200)+(119*3100)

1436100

In [46]:
# Diferença (ICV / Me / Doc)
(1182*300)+(109*600)+(119*900)

527100

In [47]:
(1182*700) - (1182*300)

472800

### 3.1 CAPES + CNPQ <a name="capes-cnpq"></a>

In [48]:
# Valor anterior ( Me / Doc)
valor_anterior = (1291*1500)+(1308*2200)
valor_anterior

4814100

In [49]:
# Valor anterior ( Me / Doc)
valor_posterior = (1291*2200)+(1308*3100)
valor_posterior

6895000

In [50]:
valor_posterior - valor_anterior

2080900

In [51]:
variacao = (valor_posterior/valor_anterior-1)*100

In [52]:
variacao

43.22510957395982

## 4. Cruzamento com tabela de reajuste <a name="cruzamento-tabela"></a>

In [53]:
df_2022_ce.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4500 entries, 2396 to 166787
Data columns (total 32 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Ano Referência             4500 non-null   object
 1   Processo                   4500 non-null   object
 2   Data Início Processo       4500 non-null   object
 3   Data Término Processo      4500 non-null   object
 4   Beneficiário               4500 non-null   object
 5   Linha de Fomento           4500 non-null   object
 6   Modalidade                 4500 non-null   object
 7   Categoria/Nível            924 non-null    object
 8   Nome Chamada               4500 non-null   object
 9   Programa CNPq              4500 non-null   object
 10  Grande Área                4500 non-null   object
 11  Área                       4500 non-null   object
 12  Subárea                    4500 non-null   object
 13  Instituição Origem         4475 non-null   object
 14  Sigla UF Origem            4475 non-null   object
 15  País Origem                4500 non-null   object
 16  Instituição Destino        4500 non-null   object
 17  Sigla Instituição Destino  4500 non-null   object
 18  Sigla Instituição Macro    4500 non-null   object
 19  Cidade Destino             4500 non-null   object
 20  Sigla UF Destino           4500 non-null   object
 21  Região                     4500 non-null   object
 22  País Destino               4500 non-null   object
 23  Título do Projeto          4322 non-null   object
 24  Palavra Chave              821 non-null    object
 25  Plano Interno              4500 non-null   object
 26  UO                         4500 non-null   object
 27  Fonte Recurso              4500 non-null   object
 28  Natureza de Despesa        4500 non-null   object
 29  Valor Pago                 4500 non-null   float64
 30  dtg_inicio                 4500 non-null   datetime64[ns]
 31  dtg_fim                    4500 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(1), object(29)
memory usage: 1.1+ MB

In [54]:
df_2022_ce.loc[df_2022_ce.Modalidade == 'GD - Doutorado']

3,Ano Referência,Processo,Data Início Processo,Data Término Processo,Beneficiário,Linha de Fomento,Modalidade,Categoria/Nível,Nome Chamada,Programa CNPq,...,País Destino,Título do Projeto,Palavra Chave,Plano Interno,UO,Fonte Recurso,Natureza de Despesa,Valor Pago,dtg_inicio,dtg_fim
22884,2022,140428/2022-4,2022-09-01 00:00:00,2023-08-31 00:00:00,Pedro Henrique de Lima Gomes,Bolsas de Doutorado,GD - Doutorado,NaN,CH MAI/DAI 2020 - Chamada CNPq Nº 12/2020 - Pr...,PROGRAMA DE TECNOLOGIA E INOVAÇÂO,...,BRA - Brasil,Fortalecimento da pesquisa e ações inovadoras ...,NaN,4947E104G21,FUNDO NACIONAL DE DESENV.CIENT.E TECNOLOGICO,0180365009,339018,8800.00,2022-09-01,2023-08-31
24267,2022,140546/2022-7,2019-07-01 00:00:00,2023-06-30 00:00:00,Alyce Hélida Bastos de Sousa,Bolsas de Doutorado,GD - Doutorado,NaN,GM-GD 2022 - Chamada CNPq nº 07/2022 - Apoio à...,Programa Institucional de Bolsas de Pós-Gradua...,...,BRA - Brasil,Manutenção da excelência acadêmica do POSDEHA,NaN,9600,CONSELHO NAC.DE DESENV.CIENTIF.E TECNOLOGICO,0100000000,339018,10376.00,2019-07-01,2023-06-30
25205,2022,140570/2022-5,2021-09-01 00:00:00,2022-08-31 00:00:00,Cristine Soares Vidal,Bolsas de Doutorado,GD - Doutorado,NaN,GM-GD 2022 - Chamada CNPq nº 07/2022 - Apoio à...,Programa Institucional de Bolsas de Pós-Gradua...,...,BRA - Brasil,"Apoio à Pesquisa Científica, Tecnológica e de ...",NaN,9600,CONSELHO NAC.DE DESENV.CIENTIF.E TECNOLOGICO,0100000000,339018,10376.00,2021-09-01,2022-08-31
25882,2022,161533/2022-1,2021-03-01 00:00:00,2025-02-28 00:00:00,Francisca Géssica Oliveira Silva,Bolsas de Doutorado,GD - Doutorado,NaN,GM-GD 2022 - Chamada CNPq nº 07/2022 - Apoio à...,Programa Institucional de Bolsas de Pós-Gradua...,...,BRA - Brasil,Pesquisa básica e translacional no Programa de...,NaN,9600,CONSELHO NAC.DE DESENV.CIENTIF.E TECNOLOGICO,0100000000,339018,5188.00,2021-03-01,2025-02-28
25898,2022,140496/2022-0,2022-09-01 00:00:00,2026-03-31 00:00:00,Francisco Mateus Alves Guimarães,Bolsas de Doutorado,GD - Doutorado,NaN,GM-GD 2022 - Chamada CNPq nº 07/2022 - Apoio à...,Programa Institucional de Bolsas de Pós-Gradua...,...,BRA - Brasil,Programa de Bolsas de Mestrado e Doutorado - P...,NaN,9600,CONSELHO NAC.DE DESENV.CIENTIF.E TECNOLOGICO,0100000000,339018,10376.00,2022-09-01,2026-03-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164266,2022,140334/2019-0,2020-04-01 00:00:00,2024-03-31 00:00:00,Vicente de Castro Sanders Neto,Bolsas de Doutorado,GD - Doutorado,NaN,GM/GD - Cotas do Programa de Pós-Graduação,Programa Institucional de Bolsas de Pós-Gradua...,...,BRA - Brasil,NaN,NaN,9992,CONSELHO NAC.DE DESENV.CIENTIF.E TECNOLOGICO,0100000000,339018,4334.00,2020-04-01,2024-03-31
164267,2022,140335/2019-6,2020-03-01 00:00:00,2023-02-28 00:00:00,Vicente Elício Porfiro Sales Gonçalves da Silva,Bolsas de Doutorado,GD - Doutorado,NaN,GM/GD - Cotas do Programa de Pós-Graduação,Programa Institucional de Bolsas de Pós-Gradua...,...,BRA - Brasil,NaN,NaN,9992,CONSELHO NAC.DE DESENV.CIENTIF.E TECNOLOGICO,0100000000,339018,2364.00,2020-03-01,2023-02-28
164272,2022,141899/2018-2,2019-03-01 00:00:00,2022-02-28 00:00:00,Victor Costa Porto,Bolsas de Doutorado,GD - Doutorado,NaN,GM/GD - Cotas do Programa de Pós-Graduação,Programa Institucional de Bolsas de Pós-Gradua...,...,BRA - Brasil,NaN,NaN,9992,CONSELHO NAC.DE DESENV.CIENTIF.E TECNOLOGICO,0100000000,339018,394.00,2019-03-01,2022-02-28
164283,2022,140431/2020-9,2022-09-01 00:00:00,2023-08-31 00:00:00,Victor Manuel Tegoma Ruiz,Bolsas de Doutorado,GD - Doutorado,NaN,GM/GD - Cotas do Programa de Pós-Graduação,Programa Institucional de Bolsas de Pós-Gradua...,...,BRA - Brasil,NaN,NaN,9992,CONSELHO NAC.DE DESENV.CIENTIF.E TECNOLOGICO,0100000000,339018,4334.00,2022-09-01,2023-08-31
164640,2022,142565/2020-2,2021-09-01 00:00:00,2022-08-31 00:00:00,Samuel Oliveira Saturno,Bolsas de Doutorado,GD - Doutorado,NaN,CHA DAI 2018 - Chamada Pública CNPq Nº 23/2018...,Programa Especial de Inovação e Tecnologia,...,BRA - Brasil,Monitoramento e Localização para Cidades Intel...,NaN,9993,CONSELHO NAC.DE DESENV.CIENTIF.E TECNOLOGICO,0100000000,339018,28534.00,2021-09-01,2022-08-31

In [55]:
cp_df_2022_ce = df_2022_ce.copy()

In [56]:
cp_df_2022_ce['Categoria/Nível'].fillna('-', inplace=True)

In [57]:
modalidade_ce = cp_df_2022_ce.groupby(['Modalidade', 'Categoria/Nível'])['Beneficiário'].nunique().reset_index()

modalidade_ce['Sigla'] = modalidade_ce['Modalidade'].apply(lambda x: x.split(' - ')[0])

modalidade_ce['chave'] = modalidade_ce['Sigla'] + ' ' + modalidade_ce['Categoria/Nível']

modalidade_ce = modalidade_ce[['chave','Modalidade','Beneficiário']]
modalidade_ce.columns = ['chave','descricao','n_beneficiarios']
modalidade_ce

    chave                                     descricao  n_beneficiarios
0   AED -       AED - Auxílio a Editoração e Publicação                4
1   APQ -                      APQ - Auxílio a Pesquisa              109
2   ARC -         ARC - Promoção de Eventos Científicos                8
3   AT 1A                 AT - Apoio Técnico a Pesquisa               24
4   AT 2A                 AT - Apoio Técnico a Pesquisa                5
5   ATP A      ATP - Apoio Técnico em Extensão no País                34
6   ATP B      ATP - Apoio Técnico em Extensão no País                15
7   DCR A     DCR - Desenvolvimento Cientifico Regional                1
8   DCR B     DCR - Desenvolvimento Cientifico Regional                4
9   DCR C     DCR - Desenvolvimento Cientifico Regional               15
10  DT 1D    DT - Produtividade Desen. Tec. e Extensão                 5
11   DT 2    DT - Produtividade Desen. Tec. e Extensão                21
12  DTI A  DTI - Desenvolvimento Tecnológico Industrial                9
13  DTI B  DTI - Desenvolvimento Tecnológico Industrial               21
14  DTI C  DTI - Desenvolvimento Tecnológico Industrial               38
15   EV 1                   EV - Especialista Visitante                2
16   EV 2                   EV - Especialista Visitante                1
17  EXP B                        EXP - Extensão no País                1
18  EXP C                        EXP - Extensão no País               14
19   GD -                                GD - Doutorado              142
20   GM -                                 GM - Mestrado              210
21   IC -                     IC - Iniciação Científica             1817
22  ICJ -             ICJ - Iniciação Científica Júnior              389
23   IT -                    IT - Iniciação Tecnológica              207
24  ITC A           ITC - Iniciação Tecnológica em TICs                5
25  ITI A      ITI - Iniciação Tecnológica e Industrial               35
26  ITI B      ITI - Iniciação Tecnológica e Industrial                1
27  PAV 2             PAV - Bolsa Pesquisador-Avaliador                1
28  PDI -               PDI - Pos-doutorado Empresarial                1
29  PDJ -                    PDJ - Pós-doutorado Júnior               16
30  PDS -                    PDS - Pós-doutorado Sênior                2
31  PQ 1A                PQ - Produtividade em Pesquisa               22
32  PQ 1B                PQ - Produtividade em Pesquisa               20
33  PQ 1C                PQ - Produtividade em Pesquisa               45
34  PQ 1D                PQ - Produtividade em Pesquisa               85
35   PQ 2                PQ - Produtividade em Pesquisa              273
36  PQ SR                PQ - Produtividade em Pesquisa                3
37   PV -                    PV - Pesquisador Visitante                1
38   PV 1                    PV - Pesquisador Visitante                3
39  SET A             SET - Fixação de Recursos Humanos                1
40  SET B             SET - Fixação de Recursos Humanos                2
41  SET C             SET - Fixação de Recursos Humanos                7
42  SET D             SET - Fixação de Recursos Humanos                2
43  SET E             SET - Fixação de Recursos Humanos                3
44  SET F             SET - Fixação de Recursos Humanos                7
45  SET G             SET - Fixação de Recursos Humanos               35
46  SET H             SET - Fixação de Recursos Humanos                5
47  SET I             SET - Fixação de Recursos Humanos                8
48  SWP -             SWP - Doutorado-Sanduiche no Pais                1

In [58]:
cp_df_2022_ce.loc[(cp_df_2022_ce.Modalidade == "DT - Produtividade Desen. Tec. e Extensão ") & (cp_df_2022_ce['Categoria/Nível'] == '2'	)].head(2)

3,Ano Referência,Processo,Data Início Processo,Data Término Processo,Beneficiário,Linha de Fomento,Modalidade,Categoria/Nível,Nome Chamada,Programa CNPq,...,País Destino,Título do Projeto,Palavra Chave,Plano Interno,UO,Fonte Recurso,Natureza de Despesa,Valor Pago,dtg_inicio,dtg_fim
131941,2022,315722/2018-5,2021-11-01 00:00:00,2022-04-30 00:00:00,Auzuir Ripardo de Alexandria,Bolsas de Produtividade em Pesquisa e Tecnologia,DT - Produtividade Desen. Tec. e Extensão,2,DT - 2018 - Chamada CNPq Nº 17/2018 - Produtiv...,Programa de Tecnologias Médicas e da Saúde,...,BRA - Brasil,Desenvolvimento de sistema para simulação de c...,"Anatomia, Aplicativo para dispositivos móvei...",9647,CONSELHO NAC.DE DESENV.CIENTIF.E TECNOLOGICO,0100000000,339018,2200.00,2021-11-01,2022-04-30
131969,2022,314903/2018-6,2022-08-01 00:00:00,2024-07-31 00:00:00,Diego Lomonaco Vasconcelos de Oliveira,Bolsas de Produtividade em Pesquisa e Tecnologia,DT - Produtividade Desen. Tec. e Extensão,2,DT - 2018 - Chamada CNPq Nº 17/2018 - Produtiv...,Programa de Desenvolvimento Tecnológico e Indu...,...,BRA - Brasil,Desenvolvimento tecnológico de polímeros de al...,"inovação tecnológica, lignina, líquido da c...",9647,CONSELHO NAC.DE DESENV.CIENTIF.E TECNOLOGICO,0100000000,339018,2200.00,2022-08-01,2024-07-31

In [59]:
tabela_reajuste = pd.read_csv(path+'tabela_reajuste.csv')
tabela_reajuste['Valor Atual'] = tabela_reajuste['Valor Atual'].apply(lambda x: float(x.replace('.','').replace(',','.')))
tabela_reajuste['Novo Valor'] = tabela_reajuste['Novo Valor'].apply(lambda x: float(x.replace('.','').replace(',','.')))
tabela_reajuste['chave'] = tabela_reajuste['Sigla']  + ' ' + tabela_reajuste['Categ/ Nível']
tabela_reajuste

,Modalidade,Sigla,Categ/ Nível,Valor Atual,Novo Valor,chave
0,Apoio Técnico à Pesquisa,AT,NS,550.00,770.00,AT NS
1,Apoio Técnico à Pesquisa,AT,NM,400.00,560.00,AT NM
2,Desenvolvimento Científico e Tecnológico Regional,DCR,A,6200.00,7750.00,DCR A
3,Desenvolvimento Científico e Tecnológico Regional,DCR,B,5200.00,6500.00,DCR B
4,Desenvolvimento Científico e Tecnológico Regional,DCR,C,4200.00,5250.00,DCR C
5,Doutorado,GD,-,2200.00,3100.00,GD -
6,Doutorado Sanduíche,SWP,-,2200.00,3100.00,SWP -
7,Doutorado Sanduíche Empresarial,SWI,-,2200.00,3100.00,SWI -
8,Iniciação Científica,IC,-,400.00,700.00,IC -
9,Iniciação Científica Júnior,ICJ,-,100.00,300.00,ICJ -
10,Iniciação Tecnológica,IT,-,400.00,700.00,IT -
11,Mestrado,GM,-,1500.00,2100.00,GM -
12,Pesquisador Visitante,PV,1,5200.00,6500.00,PV 1
13,Pós-doutorado Sênior,PDS,-,4400.00,5500.00,PDS -
14,Pós-doutorado Júnior,PDJ,-,4100.00,5200.00,PDJ -
15,Pós-doutorado Empresarial,PDI,-,4100.00,5200.00,PDI -
16,Produtividade em Pesquisa,PQ,1A,1300.00,1560.00,PQ 1A
17,Produtividade em Pesquisa,PQ,1B,1100.00,1320.00,PQ 1B
18,Produtividade em Pesquisa,PQ,1C,1100.00,1320.00,PQ 1C
19,Produtividade em Pesquisa,PQ,1D,1000.00,1200.00,PQ 1D
20,Produtividade em Desenvolvimento Tecnológico\n...,DT,1A,1300.00,1560.00,DT 1A
21,Produtividade em Desenvolvimento Tecnológico\n...,DT,1B,1100.00,1320.00,DT 1B
22,Produtividade em Desenvolvimento Tecnológico\n...,DT,1C,1100.00,1320.00,DT 1C
23,Produtividade em Desenvolvimento Tecnológico\n...,DT,1D,1000.00,1200.00,DT 1D

In [60]:
cp_df_2022_ce.columns

Index(['Ano Referência', 'Processo', 'Data Início Processo',
       'Data Término Processo', 'Beneficiário', 'Linha de Fomento',
       'Modalidade', 'Categoria/Nível', 'Nome Chamada', 'Programa CNPq',
       'Grande Área', 'Área', 'Subárea', 'Instituição Origem',
       'Sigla UF Origem', 'País Origem', 'Instituição Destino',
       'Sigla Instituição Destino', 'Sigla Instituição Macro',
       'Cidade Destino', 'Sigla UF Destino', 'Região', 'País Destino',
       'Título do Projeto', 'Palavra Chave', 'Plano Interno', 'UO',
       'Fonte Recurso', 'Natureza de Despesa', 'Valor Pago', 'dtg_inicio',
       'dtg_fim'],
      dtype='object', name=3)

In [61]:
cp_df_2022_ce.loc[cp_df_2022_ce.Modalidade == 'AT - Apoio Técnico a Pesquisa'][['Ano Referência', 'Processo', 'Data Início Processo',
       'Data Término Processo', 'Beneficiário', 'Linha de Fomento',
       'Modalidade', 'Categoria/Nível', 'Nome Chamada', 'Programa CNPq',
       'Grande Área', 'Área', 'Subárea','Instituição Destino',
       'Sigla Instituição Destino', 'Sigla Instituição Macro', 'Sigla UF Destino', 
       'Título do Projeto',  'Valor Pago', 'dtg_inicio',
       'dtg_fim']].head()

3,Ano Referência,Processo,Data Início Processo,Data Término Processo,Beneficiário,Linha de Fomento,Modalidade,Categoria/Nível,Nome Chamada,Programa CNPq,...,Área,Subárea,Instituição Destino,Sigla Instituição Destino,Sigla Instituição Macro,Sigla UF Destino,Título do Projeto,Valor Pago,dtg_inicio,dtg_fim
8880,2022,372103/2022-7,2022-08-01 00:00:00,2024-07-31 00:00:00,Alexandre Danton Viana Pinheiro,Bolsas de Apoio Técnico,AT - Apoio Técnico a Pesquisa,1A,Universal 2021 - Chamada CNPq/MCTI/FNDCT Nº 18...,PROGRAMA BASICO DE FARMACOLOGIA,...,Farmacologia,Farmacologia Bioquímica e Molecular,Universidade Federal do Ceará,UFC,UFC,CE,Estudo da associação entre a obesidade e os me...,2200.00,2022-08-01,2024-07-31
8962,2022,371079/2022-5,2020-01-01 00:00:00,2023-12-31 00:00:00,Andréa Cintia Laurindo Porto,Bolsas de Apoio Técnico,AT - Apoio Técnico a Pesquisa,1A,Universal 2021 - Chamada CNPq/MCTI/FNDCT Nº 18...,PROGRAMA BASICO DE SAUDE COLETIVA,...,Saúde Coletiva,Saúde Pública,Universidade de Fortaleza,UNIFOR,UNIFOR,CE,PROGRAMA DE PROMOÇÃO DA SAÚDE VOCAL AMPARADO P...,4400.00,2020-01-01,2023-12-31
9291,2022,371008/2022-0,2021-05-01 00:00:00,2022-03-31 00:00:00,Francisco Carlos Freire Nunes Junior,Bolsas de Apoio Técnico,AT - Apoio Técnico a Pesquisa,1A,Universal 2021 - Chamada CNPq/MCTI/FNDCT Nº 18...,PROGRAMA BASICO DE ENGENHARIA ELETRICA,...,Engenharia Elétrica,Sistemas de Telecomunicações,Universidade Federal do Ceará,UFC,UFC,CE,Superfícies Refletoras Aéreas Inteligentes em ...,4400.00,2021-05-01,2022-03-31
9347,2022,372334/2022-9,2021-12-01 00:00:00,2022-11-30 00:00:00,Georlan Gomes E Silva Júnior,Bolsas de Apoio Técnico,AT - Apoio Técnico a Pesquisa,2A,Universal 2021 - Chamada CNPq/MCTI/FNDCT Nº 18...,PROGRAMA BASICO DE ENGENHARIA ELETRICA,...,Engenharia Elétrica,Conversão e Retificação da Energia Elétrica,Universidade Federal do Ceará,UFC,UFC,CE,Projeto e construção de sistema de acionamento...,1200.00,2021-12-01,2022-11-30
9371,2022,371067/2022-7,2022-11-01 00:00:00,2023-08-31 00:00:00,Gisely de Lima freitas,Bolsas de Apoio Técnico,AT - Apoio Técnico a Pesquisa,1A,Universal 2021 - Chamada CNPq/MCTI/FNDCT Nº 18...,PROGRAMA BASICO DE FARMACOLOGIA,...,Farmacologia,Farmacologia Bioquímica e Molecular,Universidade Federal do Ceará,UFC,UFC,CE,Estudo da associação entre a obesidade e os me...,1650.00,2022-11-01,2023-08-31

In [62]:
cp_df_2022_ce.loc[cp_df_2022_ce.Modalidade == 'Doutorado Sanduíche Empresarial']

Empty DataFrame
Columns: [Ano Referência, Processo, Data Início Processo, Data Término Processo, Beneficiário, Linha de Fomento, Modalidade, Categoria/Nível, Nome Chamada, Programa CNPq, Grande Área, Área, Subárea, Instituição Origem, Sigla UF Origem, País Origem, Instituição Destino, Sigla Instituição Destino, Sigla Instituição Macro, Cidade Destino, Sigla UF Destino, Região, País Destino, Título do Projeto, Palavra Chave, Plano Interno, UO, Fonte Recurso, Natureza de Despesa, Valor Pago, dtg_inicio, dtg_fim]
Index: []

[0 rows x 32 columns]

In [63]:
merge = pd.merge(tabela_reajuste,modalidade_ce, how = 'outer',on='chave', indicator=True)

In [64]:
merge._merge.value_counts()

right_only    31
both          18
left_only      6
Name: _merge, dtype: int64

In [65]:
merge.loc[merge._merge == 'left_only'][['Modalidade','chave']]

                                           Modalidade  chave
0                            Apoio Técnico à Pesquisa  AT NS
1                            Apoio Técnico à Pesquisa  AT NM
7                     Doutorado Sanduíche Empresarial  SWI -
20  Produtividade em Desenvolvimento Tecnológico\n...  DT 1A
21  Produtividade em Desenvolvimento Tecnológico\n...  DT 1B
22  Produtividade em Desenvolvimento Tecnológico\n...  DT 1C

In [66]:
merge.loc[merge._merge == 'right_only'][['descricao','chave']]

                                       descricao  chave
24       AED - Auxílio a Editoração e Publicação  AED -
25                      APQ - Auxílio a Pesquisa  APQ -
26         ARC - Promoção de Eventos Científicos  ARC -
27                 AT - Apoio Técnico a Pesquisa  AT 1A
28                 AT - Apoio Técnico a Pesquisa  AT 2A
29      ATP - Apoio Técnico em Extensão no País   ATP A
30      ATP - Apoio Técnico em Extensão no País   ATP B
31    DT - Produtividade Desen. Tec. e Extensão    DT 2
32  DTI - Desenvolvimento Tecnológico Industrial  DTI A
33  DTI - Desenvolvimento Tecnológico Industrial  DTI B
34  DTI - Desenvolvimento Tecnológico Industrial  DTI C
35                   EV - Especialista Visitante   EV 1
36                   EV - Especialista Visitante   EV 2
37                        EXP - Extensão no País  EXP B
38                        EXP - Extensão no País  EXP C
39           ITC - Iniciação Tecnológica em TICs  ITC A
40      ITI - Iniciação Tecnológica e Industrial  ITI A
41      ITI - Iniciação Tecnológica e Industrial  ITI B
42             PAV - Bolsa Pesquisador-Avaliador  PAV 2
43                PQ - Produtividade em Pesquisa   PQ 2
44                PQ - Produtividade em Pesquisa  PQ SR
45                    PV - Pesquisador Visitante   PV -
46             SET - Fixação de Recursos Humanos  SET A
47             SET - Fixação de Recursos Humanos  SET B
48             SET - Fixação de Recursos Humanos  SET C
49             SET - Fixação de Recursos Humanos  SET D
50             SET - Fixação de Recursos Humanos  SET E
51             SET - Fixação de Recursos Humanos  SET F
52             SET - Fixação de Recursos Humanos  SET G
53             SET - Fixação de Recursos Humanos  SET H
54             SET - Fixação de Recursos Humanos  SET I

In [67]:
resumo_reajuste_ce = merge.loc[merge._merge == 'both'][['Modalidade','chave','Valor Atual','Novo Valor','n_beneficiarios']]
resumo_reajuste_ce

,Modalidade,chave,Valor Atual,Novo Valor,n_beneficiarios
2,Desenvolvimento Científico e Tecnológico Regional,DCR A,6200.00,7750.00,1.00
3,Desenvolvimento Científico e Tecnológico Regional,DCR B,5200.00,6500.00,4.00
4,Desenvolvimento Científico e Tecnológico Regional,DCR C,4200.00,5250.00,15.00
5,Doutorado,GD -,2200.00,3100.00,142.00
6,Doutorado Sanduíche,SWP -,2200.00,3100.00,1.00
8,Iniciação Científica,IC -,400.00,700.00,1817.00
9,Iniciação Científica Júnior,ICJ -,100.00,300.00,389.00
10,Iniciação Tecnológica,IT -,400.00,700.00,207.00
11,Mestrado,GM -,1500.00,2100.00,210.00
12,Pesquisador Visitante,PV 1,5200.00,6500.00,3.00
13,Pós-doutorado Sênior,PDS -,4400.00,5500.00,2.00
14,Pós-doutorado Júnior,PDJ -,4100.00,5200.00,16.00
15,Pós-doutorado Empresarial,PDI -,4100.00,5200.00,1.00
16,Produtividade em Pesquisa,PQ 1A,1300.00,1560.00,22.00
17,Produtividade em Pesquisa,PQ 1B,1100.00,1320.00,20.00
18,Produtividade em Pesquisa,PQ 1C,1100.00,1320.00,45.00
19,Produtividade em Pesquisa,PQ 1D,1000.00,1200.00,85.00
23,Produtividade em Desenvolvimento Tecnológico\n...,DT 1D,1000.00,1200.00,5.00

In [68]:
resumo_reajuste_ce['soma_valor_atual'] = resumo_reajuste_ce['Valor Atual']*resumo_reajuste_ce['n_beneficiarios']
resumo_reajuste_ce['soma_novo_valor'] = resumo_reajuste_ce['Novo Valor']*resumo_reajuste_ce['n_beneficiarios']

resumo_reajuste_ce['dif'] = resumo_reajuste_ce['soma_novo_valor']  - resumo_reajuste_ce['soma_valor_atual']

In [69]:
resumo_reajuste_ce

,Modalidade,chave,Valor Atual,Novo Valor,n_beneficiarios,soma_valor_atual,soma_novo_valor,dif
2,Desenvolvimento Científico e Tecnológico Regional,DCR A,6200.00,7750.00,1.00,6200.00,7750.00,1550.00
3,Desenvolvimento Científico e Tecnológico Regional,DCR B,5200.00,6500.00,4.00,20800.00,26000.00,5200.00
4,Desenvolvimento Científico e Tecnológico Regional,DCR C,4200.00,5250.00,15.00,63000.00,78750.00,15750.00
5,Doutorado,GD -,2200.00,3100.00,142.00,312400.00,440200.00,127800.00
6,Doutorado Sanduíche,SWP -,2200.00,3100.00,1.00,2200.00,3100.00,900.00
8,Iniciação Científica,IC -,400.00,700.00,1817.00,726800.00,1271900.00,545100.00
9,Iniciação Científica Júnior,ICJ -,100.00,300.00,389.00,38900.00,116700.00,77800.00
10,Iniciação Tecnológica,IT -,400.00,700.00,207.00,82800.00,144900.00,62100.00
11,Mestrado,GM -,1500.00,2100.00,210.00,315000.00,441000.00,126000.00
12,Pesquisador Visitante,PV 1,5200.00,6500.00,3.00,15600.00,19500.00,3900.00
13,Pós-doutorado Sênior,PDS -,4400.00,5500.00,2.00,8800.00,11000.00,2200.00
14,Pós-doutorado Júnior,PDJ -,4100.00,5200.00,16.00,65600.00,83200.00,17600.00
15,Pós-doutorado Empresarial,PDI -,4100.00,5200.00,1.00,4100.00,5200.00,1100.00
16,Produtividade em Pesquisa,PQ 1A,1300.00,1560.00,22.00,28600.00,34320.00,5720.00
17,Produtividade em Pesquisa,PQ 1B,1100.00,1320.00,20.00,22000.00,26400.00,4400.00
18,Produtividade em Pesquisa,PQ 1C,1100.00,1320.00,45.00,49500.00,59400.00,9900.00
19,Produtividade em Pesquisa,PQ 1D,1000.00,1200.00,85.00,85000.00,102000.00,17000.00
23,Produtividade em Desenvolvimento Tecnológico\n...,DT 1D,1000.00,1200.00,5.00,5000.00,6000.00,1000.00

In [70]:
resumo_reajuste_ce['n_beneficiarios'].sum()

2985.0

In [71]:
resumo_reajuste_ce.soma_valor_atual.sum()

1852300.0

In [72]:
resumo_reajuste_ce.soma_novo_valor.sum()

2877320.0

In [73]:
resumo_reajuste_ce.dif.sum()

1025020.0

In [74]:
resumo_reajuste_ce.groupby(['Modalidade','chave'])['n_beneficiarios'].sum().astype(int).reset_index().sort_values(by='n_beneficiarios', ascending = False)

                                           Modalidade  chave  n_beneficiarios
5                                Iniciação Científica   IC -             1817
6                         Iniciação Científica Júnior  ICJ -              389
8                                            Mestrado   GM -              210
7                               Iniciação Tecnológica   IT -              207
3                                           Doutorado   GD -              142
14                          Produtividade em Pesquisa  PQ 1D               85
13                          Produtividade em Pesquisa  PQ 1C               45
11                          Produtividade em Pesquisa  PQ 1A               22
12                          Produtividade em Pesquisa  PQ 1B               20
16                               Pós-doutorado Júnior  PDJ -               16
2   Desenvolvimento Científico e Tecnológico Regional  DCR C               15
10  Produtividade em Desenvolvimento Tecnológico\n...  DT 1D                5
1   Desenvolvimento Científico e Tecnológico Regional  DCR B                4
9                               Pesquisador Visitante   PV 1                3
17                               Pós-doutorado Sênior  PDS -                2
15                          Pós-doutorado Empresarial  PDI -                1
4                                 Doutorado Sanduíche  SWP -                1
0   Desenvolvimento Científico e Tecnológico Regional  DCR A                1

In [75]:
resumo_reajuste_ce.to_csv(arquivos+'resumo_reajuste_ce.csv')

In [76]:
# Capes: 
bolsas_mst = 1182
bolsas_doc = 1189
bolsas_pos_doc = 111

valor_anterior_capes = (bolsas_mst*1500)+(bolsas_doc*2200)+(bolsas_pos_doc*4100)
valor_novo_capes = (bolsas_mst*2200)+(bolsas_doc*3100)+(bolsas_pos_doc*5200)

reajuste_capes =valor_novo_capes - valor_anterior_capes

In [77]:
valor_anterior_capes

4843900

In [78]:
valor_novo_capes

6863500

In [79]:
reajuste_capes

2019600

In [80]:
resumo_reajuste_ce.dif.sum() + reajuste_capes

3044620.0

## 5. Distribuição das bolsas no Ceará <a name="distribuicao-bolsas-ce"></a>

In [81]:
# df_2022_ce.loc[df_2022_ce['dtg_fim'].dt.year != 2022]['Grande Área'].value_counts()

In [82]:
resumo_gArea_ce = df_2022_ce['Grande Área'].value_counts().reset_index()
resumo_gArea_ce.columns = ['grande_area','qtd_bolsas']
resumo_gArea_ce

                   grande_area  qtd_bolsas
0   Ciências Exatas e da Terra        1119
1            Ciências da Saúde         748
2                  Engenharias         532
3             Ciências Humanas         528
4            Ciências Agrárias         497
5          Ciências Biológicas         495
6   Ciências Sociais Aplicadas         253
7                  Tecnologias         136
8  Lingüística, Letras e Artes         135
9                        Outra          57

In [83]:
resumo_gArea_ce_v2 = df_2022_ce.groupby('Grande Área')['Beneficiário'].nunique().reset_index()
resumo_gArea_ce_v2.columns = ['grande_area','qtd_beneficiarios']
resumo_gArea_ce_v2.sort_values(by='qtd_beneficiarios',ascending=False)

                   grande_area  qtd_beneficiarios
2   Ciências Exatas e da Terra                802
5            Ciências da Saúde                607
3             Ciências Humanas                457
0            Ciências Agrárias                422
6                  Engenharias                408
1          Ciências Biológicas                402
4   Ciências Sociais Aplicadas                210
9                  Tecnologias                125
7  Lingüística, Letras e Artes                115
8                        Outra                 52

In [84]:
montante_gArea_ce = df_2022_ce.groupby('Grande Área')['Valor Pago'].sum().reset_index()
montante_gArea_ce.columns = ['grande_area','valor']
montante_gArea_ce.sort_values(by='valor', ascending =False)

                   grande_area      valor
2   Ciências Exatas e da Terra 6095060.00
1          Ciências Biológicas 5262960.00
6                  Engenharias 4848019.81
5            Ciências da Saúde 4432537.21
0            Ciências Agrárias 3868716.57
3             Ciências Humanas 2611675.89
4   Ciências Sociais Aplicadas 1285048.49
8                        Outra  858002.00
9                  Tecnologias  507100.00
7  Lingüística, Letras e Artes  460868.00

In [85]:
grande_area_ce = pd.merge(pd.merge(resumo_gArea_ce,resumo_gArea_ce_v2, on='grande_area'), montante_gArea_ce, on ='grande_area')
grande_area_ce.to_csv(arquivos+'grande_area_ce.csv', index=False)
grande_area_ce

                   grande_area  qtd_bolsas  qtd_beneficiarios      valor
0   Ciências Exatas e da Terra        1119                802 6095060.00
1            Ciências da Saúde         748                607 4432537.21
2                  Engenharias         532                408 4848019.81
3             Ciências Humanas         528                457 2611675.89
4            Ciências Agrárias         497                422 3868716.57
5          Ciências Biológicas         495                402 5262960.00
6   Ciências Sociais Aplicadas         253                210 1285048.49
7                  Tecnologias         136                125  507100.00
8  Lingüística, Letras e Artes         135                115  460868.00
9                        Outra          57                 52  858002.00

In [86]:
resumo_g_area_modalidade = df_2022_ce.groupby(['Grande Área','Modalidade'])['Beneficiário'].nunique().reset_index()
resumo_g_area_modalidade.columns = ['grande_area','modalidade','qtd_beneficiarios'] 
resumo_g_area_modalidade['sigla'] = resumo_g_area_modalidade.modalidade.apply(lambda x: x.split(' - ')[0])
resumo_g_area_modalidade['modalidade'] = resumo_g_area_modalidade.modalidade.apply(lambda x: x.split(' - ')[1])
resumo_g_area_modalidade = resumo_g_area_modalidade[['sigla','modalidade','grande_area','qtd_beneficiarios']]

In [87]:
resumo_g_area_modalidade

,sigla,modalidade,grande_area,qtd_beneficiarios
0,AED,Auxílio a Editoração e Publicação,Ciências Agrárias,1
1,APQ,Auxílio a Pesquisa,Ciências Agrárias,10
2,ARC,Promoção de Eventos Científicos,Ciências Agrárias,1
3,ATP,Apoio Técnico em Extensão no País,Ciências Agrárias,7
4,DCR,Desenvolvimento Cientifico Regional,Ciências Agrárias,7
...,...,...,...,...
120,SET,Fixação de Recursos Humanos,Outra,4
121,DT,Produtividade Desen. Tec. e Extensão,Tecnologias,24
122,IC,Iniciação Científica,Tecnologias,86
123,ICJ,Iniciação Científica Júnior,Tecnologias,6
124,IT,Iniciação Tecnológica,Tecnologias,9

In [88]:
resumo_g_area_modalidade.to_csv(arquivos+'resumo_g_area_modalidade.csv', index=False)

In [89]:
resumo_g_area_modalidade.pivot(index='grande_area',columns='modalidade', values='qtd_beneficiarios').fillna(0).astype(int)

modalidade,Apoio Técnico a Pesquisa,Apoio Técnico em Extensão no País,Auxílio a Editoração e Publicação,Auxílio a Pesquisa,Bolsa Pesquisador-Avaliador,Desenvolvimento Cientifico Regional,Desenvolvimento Tecnológico Industrial,Doutorado,Doutorado-Sanduiche no Pais,Especialista Visitante,...,Iniciação Tecnológica e Industrial,Iniciação Tecnológica em TICs,Mestrado,Pesquisador Visitante,Pos-doutorado Empresarial,Produtividade Desen. Tec. e Extensão,Produtividade em Pesquisa,Promoção de Eventos Científicos,Pós-doutorado Júnior,Pós-doutorado Sênior
grande_area,,,,,,,,,,,,,,,,,,,,,
Ciências Agrárias,0,7,1,10,0,7,16,15,0,1,...,14,0,57,0,0,0,39,1,2,1
Ciências Biológicas,7,2,0,13,0,6,1,30,0,0,...,0,0,18,1,1,0,66,2,4,0
Ciências Exatas e da Terra,1,2,0,11,1,3,10,39,0,0,...,2,1,53,0,0,0,115,3,4,0
Ciências Humanas,1,0,3,14,0,3,0,19,0,0,...,0,2,20,1,0,0,42,0,0,1
Ciências Sociais Aplicadas,4,0,0,10,0,0,0,3,0,0,...,0,0,10,1,0,0,31,0,0,0
Ciências da Saúde,8,34,0,16,0,0,15,20,1,1,...,5,0,13,1,0,0,52,0,3,0
Engenharias,5,2,0,23,0,1,19,11,0,1,...,15,2,34,0,0,0,54,2,3,0
"Lingüística, Letras e Artes",1,2,0,1,0,0,0,5,0,0,...,0,0,0,0,0,0,9,0,0,0
Outra,2,0,0,11,0,0,6,0,0,0,...,0,0,5,0,0,0,5,0,0,0
Tecnologias,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,24,0,0,0,0

In [90]:
resumo_g_area_modalidade.pivot(index='grande_area',columns='modalidade', values='qtd_beneficiarios').fillna(0).astype(int).to_csv(arquivos+'resumo_g_area_modalidade_v2.csv')

In [91]:
resumo_modalidade_ce = df_2022_ce['Modalidade'].value_counts().reset_index()
resumo_modalidade_ce.columns = ['modalidade','qtd_bolsas']
resumo_modalidade_ce

                                      modalidade  qtd_bolsas
0                      IC - Iniciação Científica        2155
1                 PQ - Produtividade em Pesquisa         567
2              ICJ - Iniciação Científica Júnior         558
3                     IT - Iniciação Tecnológica         222
4                                  GM - Mestrado         210
5                                 GD - Doutorado         209
6                       APQ - Auxílio a Pesquisa         187
7              SET - Fixação de Recursos Humanos          81
8   DTI - Desenvolvimento Tecnológico Industrial          74
9       ATP - Apoio Técnico em Extensão no País           52
10      ITI - Iniciação Tecnológica e Industrial          43
11                 AT - Apoio Técnico a Pesquisa          30
12    DT - Produtividade Desen. Tec. e Extensão           28
13     DCR - Desenvolvimento Cientifico Regional          20
14                    PDJ - Pós-doutorado Júnior          18
15                        EXP - Extensão no País          17
16         ARC - Promoção de Eventos Científicos           8
17           ITC - Iniciação Tecnológica em TICs           5
18                    PV - Pesquisador Visitante           4
19       AED - Auxílio a Editoração e Publicação           4
20                   EV - Especialista Visitante           3
21                    PDS - Pós-doutorado Sênior           2
22             SWP - Doutorado-Sanduiche no Pais           1
23               PDI - Pos-doutorado Empresarial           1
24             PAV - Bolsa Pesquisador-Avaliador           1

In [92]:
resumo_modalidade_ce_v2 = df_2022_ce.groupby('Modalidade')['Beneficiário'].nunique().reset_index()
resumo_modalidade_ce_v2.columns = ['modalidade','qtd_beneficiarios']
resumo_modalidade_ce_v2.sort_values(by='qtd_beneficiarios',ascending=False)

                                      modalidade  qtd_beneficiarios
12                     IC - Iniciação Científica               1817
21                PQ - Produtividade em Pesquisa                413
13             ICJ - Iniciação Científica Júnior                389
11                                 GM - Mestrado                210
14                    IT - Iniciação Tecnológica                207
10                                GD - Doutorado                142
1                       APQ - Auxílio a Pesquisa                109
23             SET - Fixação de Recursos Humanos                 68
7   DTI - Desenvolvimento Tecnológico Industrial                 67
4       ATP - Apoio Técnico em Extensão no País                  49
16      ITI - Iniciação Tecnológica e Industrial                 36
3                  AT - Apoio Técnico a Pesquisa                 29
6     DT - Produtividade Desen. Tec. e Extensão                  24
5      DCR - Desenvolvimento Cientifico Regional                 20
19                    PDJ - Pós-doutorado Júnior                 16
9                         EXP - Extensão no País                 15
2          ARC - Promoção de Eventos Científicos                  8
15           ITC - Iniciação Tecnológica em TICs                  5
22                    PV - Pesquisador Visitante                  4
0        AED - Auxílio a Editoração e Publicação                  4
8                    EV - Especialista Visitante                  3
20                    PDS - Pós-doutorado Sênior                  2
18               PDI - Pos-doutorado Empresarial                  1
17             PAV - Bolsa Pesquisador-Avaliador                  1
24             SWP - Doutorado-Sanduiche no Pais                  1

In [93]:
montante_modalidade_ce = df_2022_ce.groupby('Modalidade')['Valor Pago'].sum().reset_index()
montante_modalidade_ce.columns = ['modalidade','valor']
montante_modalidade_ce.sort_values(by='valor', ascending =False)

                                      modalidade      valor
1                       APQ - Auxílio a Pesquisa 9354184.66
21                PQ - Produtividade em Pesquisa 6671480.00
12                     IC - Iniciação Científica 4216400.00
10                                GD - Doutorado 3081902.00
11                                 GM - Mestrado 1993500.00
23             SET - Fixação de Recursos Humanos  879700.00
7   DTI - Desenvolvimento Tecnológico Industrial  785660.00
5      DCR - Desenvolvimento Cientifico Regional  672200.00
2          ARC - Promoção de Eventos Científicos  451000.00
14                    IT - Iniciação Tecnológica  426800.00
19                    PDJ - Pós-doutorado Júnior  391100.00
6     DT - Produtividade Desen. Tec. e Extensão   304700.00
13             ICJ - Iniciação Científica Júnior  251100.00
4       ATP - Apoio Técnico em Extensão no País   143900.00
22                    PV - Pesquisador Visitante  127207.31
9                         EXP - Extensão no País   99060.00
8                    EV - Especialista Visitante   91500.00
3                  AT - Apoio Técnico a Pesquisa   88450.00
16      ITI - Iniciação Tecnológica e Industrial   75044.00
0        AED - Auxílio a Editoração e Publicação   52500.00
18               PDI - Pos-doutorado Empresarial   24600.00
15           ITC - Iniciação Tecnológica em TICs   22000.00
24             SWP - Doutorado-Sanduiche no Pais   15200.00
20                    PDS - Pós-doutorado Sênior    9600.00
17             PAV - Bolsa Pesquisador-Avaliador    1200.00

In [94]:
modalidade_ce = pd.merge(pd.merge(resumo_modalidade_ce,resumo_modalidade_ce_v2, on='modalidade'), montante_modalidade_ce, on ='modalidade')
modalidade_ce.to_csv(arquivos+'modalidade_ce.csv', index=False)
modalidade_ce

,modalidade,qtd_bolsas,qtd_beneficiarios,valor
0,IC - Iniciação Científica,2155,1817,4216400.00
1,PQ - Produtividade em Pesquisa,567,413,6671480.00
2,ICJ - Iniciação Científica Júnior,558,389,251100.00
3,IT - Iniciação Tecnológica,222,207,426800.00
4,GM - Mestrado,210,210,1993500.00
5,GD - Doutorado,209,142,3081902.00
6,APQ - Auxílio a Pesquisa,187,109,9354184.66
7,SET - Fixação de Recursos Humanos,81,68,879700.00
8,DTI - Desenvolvimento Tecnológico Industrial,74,67,785660.00
9,ATP - Apoio Técnico em Extensão no País,52,49,143900.00
10,ITI - Iniciação Tecnológica e Industrial,43,36,75044.00
11,AT - Apoio Técnico a Pesquisa,30,29,88450.00
12,DT - Produtividade Desen. Tec. e Extensão,28,24,304700.00
13,DCR - Desenvolvimento Cientifico Regional,20,20,672200.00
14,PDJ - Pós-doutorado Júnior,18,16,391100.00
15,EXP - Extensão no País,17,15,99060.00
16,ARC - Promoção de Eventos Científicos,8,8,451000.00
17,ITC - Iniciação Tecnológica em TICs,5,5,22000.00
18,PV - Pesquisador Visitante,4,4,127207.31
19,AED - Auxílio a Editoração e Publicação,4,4,52500.00
20,EV - Especialista Visitante,3,3,91500.00
21,PDS - Pós-doutorado Sênior,2,2,9600.00
22,SWP - Doutorado-Sanduiche no Pais,1,1,15200.00
23,PDI - Pos-doutorado Empresarial,1,1,24600.00
24,PAV - Bolsa Pesquisador-Avaliador,1,1,1200.00

In [95]:
modalidade_ce.sort_values(by='valor', ascending=False).head(5)

                       modalidade  qtd_bolsas  qtd_beneficiarios      valor
6        APQ - Auxílio a Pesquisa         187                109 9354184.66
1  PQ - Produtividade em Pesquisa         567                413 6671480.00
0       IC - Iniciação Científica        2155               1817 4216400.00
5                  GD - Doutorado         209                142 3081902.00
4                   GM - Mestrado         210                210 1993500.00

In [96]:
modalidade_ce.shape[0]

25

In [97]:
outras_modalidades = modalidade_ce.sort_values(by='valor', ascending=False).tail(20).sum()
outras_modalidades['modalidade']='Outras'
outras_modalidades

modalidade              Outras
qtd_bolsas                1172
qtd_beneficiarios          949
valor               4912521.31
dtype: object

In [98]:
cinco_mais = modalidade_ce.sort_values(by='valor', ascending=False).head(5)

In [99]:
cinco_mais = cinco_mais.append(outras_modalidades,ignore_index=True)

In [100]:
cinco_mais.to_csv(arquivos+'principais_modalidades_ce.csv')

In [101]:
outras_modalidades_v2 = modalidade_ce.sort_values(by='qtd_beneficiarios', ascending=False).tail(20).sum()
outras_modalidades_v2['modalidade']='Outras'
outras_modalidades_v2

modalidade               Outras
qtd_bolsas                  788
qtd_beneficiarios           604
valor               16670707.97
dtype: object

In [102]:
cinco_mais_v2 = modalidade_ce.sort_values(by='qtd_beneficiarios', ascending=False).head(5)

In [103]:
cinco_mais_v2 = cinco_mais_v2.append(outras_modalidades_v2,ignore_index=True)

In [104]:
cinco_mais.to_csv(arquivos+'principais_modalidades_ce_v2.csv')

In [105]:
montante_modalidade_ce = df_2022_ce.groupby('Modalidade')['Valor Pago'].sum().reset_index()
montante_modalidade_ce['grande_area'] = 'Todas'
montante_modalidade_ce.columns = ['modalidade','R$', 'grande_area'] 

montante_modalidade_ce.sort_values(by='R$', ascending =False)

                                      modalidade         R$ grande_area
1                       APQ - Auxílio a Pesquisa 9354184.66       Todas
21                PQ - Produtividade em Pesquisa 6671480.00       Todas
12                     IC - Iniciação Científica 4216400.00       Todas
10                                GD - Doutorado 3081902.00       Todas
11                                 GM - Mestrado 1993500.00       Todas
23             SET - Fixação de Recursos Humanos  879700.00       Todas
7   DTI - Desenvolvimento Tecnológico Industrial  785660.00       Todas
5      DCR - Desenvolvimento Cientifico Regional  672200.00       Todas
2          ARC - Promoção de Eventos Científicos  451000.00       Todas
14                    IT - Iniciação Tecnológica  426800.00       Todas
19                    PDJ - Pós-doutorado Júnior  391100.00       Todas
6     DT - Produtividade Desen. Tec. e Extensão   304700.00       Todas
13             ICJ - Iniciação Científica Júnior  251100.00       Todas
4       ATP - Apoio Técnico em Extensão no País   143900.00       Todas
22                    PV - Pesquisador Visitante  127207.31       Todas
9                         EXP - Extensão no País   99060.00       Todas
8                    EV - Especialista Visitante   91500.00       Todas
3                  AT - Apoio Técnico a Pesquisa   88450.00       Todas
16      ITI - Iniciação Tecnológica e Industrial   75044.00       Todas
0        AED - Auxílio a Editoração e Publicação   52500.00       Todas
18               PDI - Pos-doutorado Empresarial   24600.00       Todas
15           ITC - Iniciação Tecnológica em TICs   22000.00       Todas
24             SWP - Doutorado-Sanduiche no Pais   15200.00       Todas
20                    PDS - Pós-doutorado Sênior    9600.00       Todas
17             PAV - Bolsa Pesquisador-Avaliador    1200.00       Todas

In [106]:
montante_modalidade_ce['R$'].sum()

30229987.97

In [107]:
resumo__modalidade_g_area = df_2022_ce.groupby(['Modalidade','Grande Área'])['Valor Pago'].sum().reset_index()
resumo__modalidade_g_area.columns = ['modalidade','grande_area','R$'] 
resumo__modalidade_g_area

,modalidade,grande_area,R$
0,AED - Auxílio a Editoração e Publicação,Ciências Agrárias,12000.00
1,AED - Auxílio a Editoração e Publicação,Ciências Humanas,40500.00
2,APQ - Auxílio a Pesquisa,Ciências Agrárias,960382.57
3,APQ - Auxílio a Pesquisa,Ciências Biológicas,2158260.00
4,APQ - Auxílio a Pesquisa,Ciências Exatas e da Terra,1058900.00
...,...,...,...
120,SET - Fixação de Recursos Humanos,Ciências Humanas,10500.00
121,SET - Fixação de Recursos Humanos,Ciências da Saúde,258500.00
122,SET - Fixação de Recursos Humanos,Engenharias,77100.00
123,SET - Fixação de Recursos Humanos,Outra,54000.00
124,SWP - Doutorado-Sanduiche no Pais,Ciências da Saúde,15200.00

In [108]:
pd.concat([montante_modalidade_ce,resumo__modalidade_g_area]).to_csv(arquivos+'modalidade_gArea_ce.csv')

In [109]:
df_2022_ce.loc[df_2022_ce['Modalidade'] == 'GM - Mestrado'].head()

3,Ano Referência,Processo,Data Início Processo,Data Término Processo,Beneficiário,Linha de Fomento,Modalidade,Categoria/Nível,Nome Chamada,Programa CNPq,...,País Destino,Título do Projeto,Palavra Chave,Plano Interno,UO,Fonte Recurso,Natureza de Despesa,Valor Pago,dtg_inicio,dtg_fim
22863,2022,130842/2022-2,2022-09-01 00:00:00,2023-08-31 00:00:00,Francisco Lucas do Nascimento Lopes,Bolsas de Mestrado,GM - Mestrado,NaN,CH MAI/DAI 2020 - Chamada CNPq Nº 12/2020 - Pr...,PROGRAMA DE TECNOLOGIA E INOVAÇÂO,...,BRA - Brasil,Fortalecimento da pesquisa e ações inovadoras ...,NaN,4947E104G21,FUNDO NACIONAL DE DESENV.CIENT.E TECNOLOGICO,0180365009,339018,6000.00,2022-09-01,2023-08-31
22877,2022,130816/2022-1,2022-09-01 00:00:00,2023-08-31 00:00:00,Luis Felipe Nunes de Oliveira,Bolsas de Mestrado,GM - Mestrado,NaN,CH MAI/DAI 2020 - Chamada CNPq Nº 12/2020 - Pr...,PROGRAMA DE TECNOLOGIA E INOVAÇÂO,...,BRA - Brasil,Fortalecimento da pesquisa e ações inovadoras ...,NaN,4947E104G21,FUNDO NACIONAL DE DESENV.CIENT.E TECNOLOGICO,0180365009,339018,7500.00,2022-09-01,2023-08-31
22879,2022,130817/2022-8,2021-09-01 00:00:00,2022-08-31 00:00:00,Matheus Aragão Dias Firmino,Bolsas de Mestrado,GM - Mestrado,NaN,CH MAI/DAI 2020 - Chamada CNPq Nº 12/2020 - Pr...,PROGRAMA DE TECNOLOGIA E INOVAÇÂO,...,BRA - Brasil,Fortalecimento da pesquisa e ações inovadoras ...,NaN,4947E104G21,FUNDO NACIONAL DE DESENV.CIENT.E TECNOLOGICO,0180365009,339018,7500.00,2021-09-01,2022-08-31
22894,2022,130841/2022-6,2021-09-01 00:00:00,2022-08-31 00:00:00,Thaynan dos Santos Dias,Bolsas de Mestrado,GM - Mestrado,NaN,CH MAI/DAI 2020 - Chamada CNPq Nº 12/2020 - Pr...,PROGRAMA DE TECNOLOGIA E INOVAÇÂO,...,BRA - Brasil,Fortalecimento da pesquisa e ações inovadoras ...,NaN,4947E104G21,FUNDO NACIONAL DE DESENV.CIENT.E TECNOLOGICO,0180365009,339018,6000.00,2021-09-01,2022-08-31
24069,2022,131055/2022-4,2021-08-01 00:00:00,2022-07-31 00:00:00,Ádila Jamille Lopes Pereira Carloto,Bolsas de Mestrado,GM - Mestrado,NaN,GM-GD 2022 - Chamada CNPq nº 07/2022 - Apoio à...,Programa Institucional de Bolsas de Pós-Gradua...,...,BRA - Brasil,Manutenção da excelência acadêmica do POSDEHA,NaN,9600,CONSELHO NAC.DE DESENV.CIENTIF.E TECNOLOGICO,0100000000,339018,6000.00,2021-08-01,2022-07-31

In [110]:
df_2022_ce.loc[df_2022_ce['Modalidade'] == 'GM - Mestrado']['Beneficiário'].value_counts()

Francisco Lucas do Nascimento Lopes            1
Fernanda Naiara da Frota Lobato                1
Victor Freire Sydrião de Alencar               1
Vitória Stephani de Oliveira Costa Teixeira    1
Winston Kleine Ramalho Viana                   1
                                              ..
Larissa dos Santos Nunes                       1
Laryssa Querino da Silva Duarte                1
Laura Cunha Rebouças Lessa                     1
Lavina Sousa Araújo                            1
William Axl Silva Vasconcelos                  1
Name: Beneficiário, Length: 210, dtype: int64

In [111]:
df_2022_ce.loc[df_2022_ce['dtg_fim'].dt.year == 2022].head()

3,Ano Referência,Processo,Data Início Processo,Data Término Processo,Beneficiário,Linha de Fomento,Modalidade,Categoria/Nível,Nome Chamada,Programa CNPq,...,País Destino,Título do Projeto,Palavra Chave,Plano Interno,UO,Fonte Recurso,Natureza de Despesa,Valor Pago,dtg_inicio,dtg_fim
2399,2022,181186/2021-7,2017-09-01 00:00:00,2022-02-28 00:00:00,Pedro Wellington Lima Bezerra,Bolsas de Iniciação Tecnológica e Industrial,ITI - Iniciação Tecnológica e Industrial,B,ICMBio 2017 - CHAMADA CNPQ/ICMBIO/FAPs nº 18/2...,PROGRAMA DE BIODIVERSIDADE,...,BRA - Brasil,"Cavernas, abrigos e seu ecossistema - Pesquisa...",NaN,04181502RCA,INST.CHICO MENDES DE CONSER.DA BIODIVERSIDADE,0307442070,339018,322.00,2017-09-01,2022-02-28
5671,2022,402141/2021-0,2021-09-01 00:00:00,2022-08-31 00:00:00,Alek Sandro Dutra,Apoio a Periódicos Científicos,AED - Auxílio a Editoração e Publicação,NaN,Editoração 2021 - Chamada CNPq Nº 15/2021 - Pr...,PROGRAMA ESPECIAL DE DIFUSÃO E POPULARIZAÇÃO D...,...,BRA - Brasil,Revista Ciência Agronômica,"Engenharia Agrícola, Engenharia de Alimentos...",10009,CONSELHO NAC.DE DESENV.CIENTIF.E TECNOLOGICO,0100000000400,339020,12000.00,2021-09-01,2022-08-31
5840,2022,305212/2021-4,2021-09-01 00:00:00,2022-08-31 00:00:00,Andressa Teles Chaves,Bolsas de Apoio Técnico,ATP - Apoio Técnico em Extensão no País,A,COVID19 MCTIC/MS - Chamada MCTIC/CNPq/FNDCT/MS...,Programa Especial de Cooperação com o Ministér...,...,BRA - Brasil,"Efetividade do acesso, atendimento clínico e a...",NaN,10010,FUNDO NACIONAL DE SAUDE,6153699887,339018,4950.00,2021-09-01,2022-08-31
5852,2022,313609/2022-5,2021-09-01 00:00:00,2022-08-31 00:00:00,Carmem Lucia Magalhães de Queiroz,Bolsas de Apoio Técnico,ATP - Apoio Técnico em Extensão no País,B,COVID19 MCTIC/MS - Chamada MCTIC/CNPq/FNDCT/MS...,Programa Especial de Cooperação com o Ministér...,...,BRA - Brasil,Avaliação dos riscos de profissionais de saúde...,NaN,10010,FUNDO NACIONAL DE SAUDE,6153699887,339018,800.00,2021-09-01,2022-08-31
5894,2022,309317/2020-7,2021-09-01 00:00:00,2022-08-31 00:00:00,Francisco Marto Leal Pinheiro Júnior,Bolsas de Pesquisador/Especialista Visitante,EV - Especialista Visitante,1,COVID19 MCTIC/MS - Chamada MCTIC/CNPq/FNDCT/MS...,Programa Especial de Cooperação com o Ministér...,...,BRA - Brasil,Avaliação dos riscos de profissionais de saúde...,NaN,10010,FUNDO NACIONAL DE SAUDE,6153699887,339018,35000.00,2021-09-01,2022-08-31